version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - pwd
      - ls -alh .
      - zip -r source.zip .
      - echo "${CODEBUILD_WEBHOOK_PREV_COMMIT}"
      - set
      - COMMIT_TYPE="$(echo "${CODEBUILD_WEBHOOK_TRIGGER}" |cut -d/ -f1)"
      - COMMIT_TARGET="$(echo "${CODEBUILD_WEBHOOK_TRIGGER}" |cut -d/ -f2)"
      - |
        if [[ "${COMMIT_TYPE}"  == "branch" ]];then
          if [[ "${COMMIT_TARGET}" != "master" ]];then
            echo "aws s3 cp source.zip s3://${S3_BUCKET}/dev.zip;"
          else
            echo "aws s3 cp source.zip s3://${S3_BUCKET}/test.zip;"
          fi
        elif [[ "${COMMIT_TYPE}"  == "tag" ]];then
          echo "aws s3 cp source.zip s3://${S3_BUCKET}/prod.zip;"
        fi

