version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - export
      - echo $CODEBUILD_WEBHOOK_TRIGGER |cut -d/ -f2
  build:
    commands:
      - echo "Building all the things..."
      - echo "Built"
